# Generated by Django 5.1.7 on 2025-03-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('pee', models.BooleanField(default=False)),
                ('poop', models.BooleanField(default=False)),
                ('made_milk', models.PositiveIntegerField()),
                ('drank_milk', models.PositiveIntegerField()),
                ('remaining_milk', models.PositiveIntegerField()),
            ],
        ),
    ]
